import React, { createContext, useContext, useState, useCallback } from "react";

type Lang = "en" | "ms";

const translations = {
  en: {
    appName: "JimatMakan",
    tagline: "Save food. Save money.",
    home: "Home",
    browse: "Browse",
    addListing: "List",
    activity: "Activity",
    profile: "Profile",
    availableNow: "Available Now",
    expiringSoon: "Expiring Soon",
    forComposting: "For Composting",
    seeAll: "See all",
    searchPlaceholder: "Search surplus food...",
    timeLeft: "left",
    expired: "Expired",
    movedToCompost: "Moved to composting",
    categories: "Categories",
    restaurants: "Restaurants",
    nightMarket: "Night Market",
    students: "Students",
    composting: "Composting",
    allCategories: "All",
    rice: "Rice",
    bread: "Bread",
    vegetables: "Vegetables",
    fruits: "Fruits",
    meat: "Meat",
    seafood: "Seafood",
    pastries: "Pastries",
    deliverTo: "Location",
    howItWorks: "How It Works",
    step1Title: "Restaurants list surplus",
    step1Desc: "Excess food listed with a 2-hour freshness window",
    step2Title: "Vendors & students buy",
    step2Desc: "Night market vendors and students get quality food cheaper",
    step3Title: "Unsold → Composting",
    step3Desc: "After 2 hours, remaining food goes to composting partners",
    priceReduced: "Reduced",
    originalPrice: "Original",
    listedBy: "Listed by",
    buyNow: "Buy Now",
    compostClaim: "Claim for Composting",
    language: "Language",
    english: "English",
    malay: "Bahasa Melayu",
    impactTitle: "Your Impact",
    foodSaved: "kg food saved",
    co2Reduced: "kg CO₂ reduced",
    motivationalMsg: "Every meal saved is a step towards a greener Malaysia. Reduce waste, feed communities.",
    reorderTitle: "Order from these stores again?",
    foodSavedChart: "Food Waste Saved (kg)",
    co2ReducedChart: "CO₂ Emissions Reduced (kg)",
    esgReportTitle: "ESG Sustainability Report",
    esgReportDesc: "Generate a detailed Environmental, Social & Governance report with your food waste reduction data, carbon offset metrics, and sustainability impact analysis.",
    esgReportBtn: "Generate ESG Report",
    esgReportGenerated: "ESG report generated! Check your email.",
    totalRevenue: "Total Revenue",
    totalOrders: "Total Orders",
    revenueChart: "Revenue (RM)",
    noActivityYet: "No activity yet — charts will appear once you start ordering or selling.",
    recentSales: "Recent Sales",
    itemName: "Item Name",
    itemNamePlaceholder: "e.g. Nasi Lemak Batch",
    quantityLabel: "Quantity",
    quantityPlaceholder: "e.g. 5 kg",
    twoHourNotice: "Listings are available for 2 hours. Unsold items will be moved to composting.",
    publishListing: "Publish Listing",
    listingCreated: "Listing published successfully!",
    yourListings: "Your Listings",
    // Auth
    loginBtn: "Log In",
    signupBtn: "Sign Up",
    loginTitle: "Welcome back",
    signupTitle: "Create account",
    emailLabel: "Email",
    passwordLabel: "Password",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "e.g. Ahmad bin Ismail",
    businessNameLabel: "Business Name",
    businessNamePlaceholder: "e.g. Ahmad's Nasi Lemak",
    phoneLabel: "Phone Number",
    selectRole: "I am a...",
    roleVendor: "Vendor",
    roleVendorDesc: "Night market vendor buying surplus food at lower prices",
    roleUser: "Student",
    roleUserDesc: "Student or individual looking for affordable food",
    roleComposter: "Composter",
    roleComposterDesc: "Composting company collecting expired food materials",
    continueBtn: "Continue",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    loginError: "Invalid email or password. Try a demo account.",
    fillAllFields: "Please fill in all fields.",
    businessNameRequired: "Business name is required for vendors and composters.",
    demoAccounts: "Quick demo access",
    otpTitle: "Verify your phone",
    otpSentTo: "OTP sent to",
    otpInvalid: "Invalid code. Use 123456 for demo.",
    otpDemo: "Demo OTP code",
    verifyBtn: "Verify",
    resendOtp: "Resend code",
    resendIn: "Resend in",
    logout: "Log out",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    profileUpdated: "Profile updated",
    paymentMethods: "Payment Methods",
    addPayment: "Add Payment Method",
    tngWallet: "Touch 'n Go eWallet",
    creditDebit: "Credit / Debit Card",
    bankTransfer: "Bank Transfer (FPX)",
    tngPhone: "TNG Phone Number",
    cardNumber: "Card Number",
    cardExpiry: "Expiry (MM/YY)",
    cardCvv: "CVV",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    paymentAdded: "Payment method added",
    paymentRemoved: "Payment method removed",
    noPayments: "No payment methods yet",
    remove: "Remove",
    noResults: "No results found. Try a different search.",
    noReorderHistory: "No order history yet. Browse listings to get started!",
    storeUnavailable: "Unavailable",
    snapToAutofill: "📸 Snap photo to autofill",
    aiAnalyzing: "AI is analyzing your food...",
    aiAutofilled: "Form autofilled by AI!",
    chooseLocation: "Choose Location",
    tapToSelect: "Tap anywhere on the map to move the pin",
    confirmLocation: "Confirm Location",
    checkout: "Checkout",
    orderSummary: "Order Summary",
    quantity: "Quantity",
    subtotal: "Subtotal",
    youSave: "You save",
    selectPayment: "Select Payment",
    placeOrder: "Place Order",
    orderPlaced: "Order Placed!",
    orderConfirmation: "Your order has been placed successfully. The vendor will prepare your items for pickup.",
    backToBrowse: "Back to Browse",
    itemUnavailable: "This item is no longer available.",
    myOrders: "My Orders",
    noOrdersYet: "No orders yet. Browse listings to find food!",
    pickupLocation: "Pickup Location",
    contactVendor: "Contact vendor for pickup details",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    yourOrders: "Your Orders",
    viewAllOrders: "View All",
    confirmPickup: "Confirm Pickup",
    confirmPickupTitle: "Confirm Order Pickup",
    confirmPickupDesc: "Have you picked up this order?",
    yes: "Yes, I've picked it up",
    no: "Not yet",
    orderCompleted: "Order marked as completed!",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    notifTotalEarnings: "total earnings",
    notifViewActivity: "View your activity dashboard",
    notifPendingOrders: "pending orders",
    notifCheckOrders: "Check your orders",
    notifFoodRescued: "food rescued",
    notifViewImpact: "View your environmental impact",
    notifCO2Saved: "CO₂ reduced",
    notifPendingPickup: "orders ready for pickup",
    notifGoToOrders: "Go to your orders",
    notifOrdersCompleted: "orders completed",
    notifSaved: "saved so far",
    notifKeepSaving: "Keep saving with JimatMakan!",
    esgCheckout: "ESG Report Checkout",
    esgPurchaseSuccess: "Report Downloaded!",
    esgPurchaseSuccessDesc: "Your ESG Impact Report has been generated and downloaded to your device.",
    backToActivity: "Back to Activity",
    esgReportIncludes: "Report includes",
    esgMonthlyBreakdown: "Includes monthly breakdown data",
    esgTotal: "Total",
    esgPayAndDownload: "Pay & Download Report",
    sellerPhone: "Seller's Phone",
  },
  ms: {
    appName: "JimatMakan",
    tagline: "Jimat makanan. Jimat wang.",
    home: "Utama",
    browse: "Cari",
    addListing: "Senarai",
    activity: "Aktiviti",
    profile: "Profil",
    availableNow: "Tersedia Sekarang",
    expiringSoon: "Hampir Tamat",
    forComposting: "Untuk Kompos",
    seeAll: "Lihat semua",
    searchPlaceholder: "Cari makanan lebihan...",
    timeLeft: "lagi",
    expired: "Tamat Tempoh",
    movedToCompost: "Dipindahkan ke kompos",
    categories: "Kategori",
    restaurants: "Restoran",
    nightMarket: "Pasar Malam",
    students: "Pelajar",
    composting: "Kompos",
    allCategories: "Semua",
    rice: "Nasi",
    bread: "Roti",
    vegetables: "Sayur",
    fruits: "Buah",
    meat: "Daging",
    seafood: "Makanan Laut",
    pastries: "Pastri",
    deliverTo: "Lokasi",
    howItWorks: "Cara Ia Berfungsi",
    step1Title: "Restoran senaraikan lebihan",
    step1Desc: "Makanan lebihan disenaraikan dengan tempoh kesegaran 2 jam",
    step2Title: "Peniaga & pelajar beli",
    step2Desc: "Peniaga pasar malam dan pelajar dapat makanan berkualiti dengan harga murah",
    step3Title: "Tidak terjual → Kompos",
    step3Desc: "Selepas 2 jam, makanan selebihnya dihantar kepada rakan kompos",
    priceReduced: "Dikurangkan",
    originalPrice: "Asal",
    listedBy: "Disenaraikan oleh",
    buyNow: "Beli Sekarang",
    compostClaim: "Tuntut untuk Kompos",
    language: "Bahasa",
    english: "English",
    malay: "Bahasa Melayu",
    impactTitle: "Impak Anda",
    foodSaved: "kg makanan diselamatkan",
    co2Reduced: "kg CO₂ dikurangkan",
    motivationalMsg: "Setiap hidangan yang diselamatkan adalah langkah ke arah Malaysia yang lebih hijau. Kurangkan pembaziran, beri makan komuniti.",
    reorderTitle: "Pesan dari kedai ini lagi?",
    foodSavedChart: "Sisa Makanan Diselamatkan (kg)",
    co2ReducedChart: "Pelepasan CO₂ Dikurangkan (kg)",
    esgReportTitle: "Laporan Kelestarian ESG",
    esgReportDesc: "Jana laporan terperinci Alam Sekitar, Sosial & Tadbir Urus dengan data pengurangan sisa makanan, metrik pengimbangan karbon, dan analisis impak kelestarian anda.",
    esgReportBtn: "Jana Laporan ESG",
    esgReportGenerated: "Laporan ESG dijana! Semak e-mel anda.",
    totalRevenue: "Jumlah Pendapatan",
    totalOrders: "Jumlah Pesanan",
    revenueChart: "Pendapatan (RM)",
    noActivityYet: "Tiada aktiviti lagi — carta akan muncul selepas anda mula memesan atau menjual.",
    recentSales: "Jualan Terkini",
    itemName: "Nama Item",
    itemNamePlaceholder: "cth. Kelompok Nasi Lemak",
    quantityLabel: "Kuantiti",
    quantityPlaceholder: "cth. 5 kg",
    twoHourNotice: "Senarai tersedia selama 2 jam. Item tidak terjual akan dipindahkan ke kompos.",
    publishListing: "Terbitkan Senarai",
    listingCreated: "Senarai berjaya diterbitkan!",
    yourListings: "Senarai Anda",
    // Auth
    loginBtn: "Log Masuk",
    signupBtn: "Daftar",
    loginTitle: "Selamat kembali",
    signupTitle: "Cipta akaun",
    emailLabel: "E-mel",
    passwordLabel: "Kata laluan",
    fullNameLabel: "Nama Penuh",
    fullNamePlaceholder: "cth. Ahmad bin Ismail",
    businessNameLabel: "Nama Perniagaan",
    businessNamePlaceholder: "cth. Nasi Lemak Ahmad",
    phoneLabel: "Nombor Telefon",
    selectRole: "Saya adalah...",
    roleVendor: "Peniaga",
    roleVendorDesc: "Peniaga pasar malam membeli makanan lebihan pada harga rendah",
    roleUser: "Pelajar",
    roleUserDesc: "Pelajar atau individu mencari makanan mampu milik",
    roleComposter: "Pengkompos",
    roleComposterDesc: "Syarikat kompos mengumpul bahan makanan tamat tempoh",
    continueBtn: "Teruskan",
    noAccount: "Tiada akaun?",
    haveAccount: "Sudah ada akaun?",
    loginError: "E-mel atau kata laluan tidak sah. Cuba akaun demo.",
    fillAllFields: "Sila isi semua ruangan.",
    businessNameRequired: "Nama perniagaan diperlukan untuk peniaga dan pengkompos.",
    demoAccounts: "Akses demo pantas",
    otpTitle: "Sahkan telefon anda",
    otpSentTo: "OTP dihantar ke",
    otpInvalid: "Kod tidak sah. Guna 123456 untuk demo.",
    otpDemo: "Kod OTP demo",
    verifyBtn: "Sahkan",
    resendOtp: "Hantar semula kod",
    resendIn: "Hantar semula dalam",
    logout: "Log keluar",
    editProfile: "Sunting Profil",
    saveChanges: "Simpan Perubahan",
    cancel: "Batal",
    profileUpdated: "Profil dikemas kini",
    paymentMethods: "Kaedah Pembayaran",
    addPayment: "Tambah Kaedah Pembayaran",
    tngWallet: "Touch 'n Go eWallet",
    creditDebit: "Kad Kredit / Debit",
    bankTransfer: "Pindahan Bank (FPX)",
    tngPhone: "Nombor Telefon TNG",
    cardNumber: "Nombor Kad",
    cardExpiry: "Tarikh Luput (BB/TT)",
    cardCvv: "CVV",
    bankName: "Nama Bank",
    accountNumber: "Nombor Akaun",
    paymentAdded: "Kaedah pembayaran ditambah",
    paymentRemoved: "Kaedah pembayaran dikeluarkan",
    noPayments: "Tiada kaedah pembayaran lagi",
    remove: "Keluarkan",
    noResults: "Tiada hasil dijumpai. Cuba carian lain.",
    noReorderHistory: "Tiada sejarah pesanan lagi. Layari senarai untuk bermula!",
    storeUnavailable: "Tidak tersedia",
    snapToAutofill: "📸 Tangkap gambar untuk isi auto",
    aiAnalyzing: "AI sedang menganalisis makanan anda...",
    aiAutofilled: "Borang diisi automatik oleh AI!",
    chooseLocation: "Pilih Lokasi",
    tapToSelect: "Ketik mana-mana pada peta untuk alihkan pin",
    confirmLocation: "Sahkan Lokasi",
    checkout: "Pembayaran",
    orderSummary: "Ringkasan Pesanan",
    quantity: "Kuantiti",
    subtotal: "Jumlah kecil",
    youSave: "Anda jimat",
    selectPayment: "Pilih Pembayaran",
    placeOrder: "Buat Pesanan",
    orderPlaced: "Pesanan Dibuat!",
    orderConfirmation: "Pesanan anda telah berjaya dibuat. Peniaga akan menyediakan item anda untuk pengambilan.",
    backToBrowse: "Kembali ke Carian",
    itemUnavailable: "Item ini tidak lagi tersedia.",
    myOrders: "Pesanan Saya",
    noOrdersYet: "Tiada pesanan lagi. Layari senarai untuk mencari makanan!",
    pickupLocation: "Lokasi Pengambilan",
    contactVendor: "Hubungi peniaga untuk butiran pengambilan",
    pending: "Menunggu",
    completed: "Selesai",
    cancelled: "Dibatalkan",
    yourOrders: "Pesanan Anda",
    viewAllOrders: "Lihat Semua",
    confirmPickup: "Sahkan Pengambilan",
    confirmPickupTitle: "Sahkan Pengambilan Pesanan",
    confirmPickupDesc: "Adakah anda sudah mengambil pesanan ini?",
    yes: "Ya, saya sudah ambil",
    no: "Belum lagi",
    orderCompleted: "Pesanan ditandakan selesai!",
    notifications: "Pemberitahuan",
    noNotifications: "Tiada pemberitahuan lagi",
    notifTotalEarnings: "jumlah pendapatan",
    notifViewActivity: "Lihat papan pemuka aktiviti anda",
    notifPendingOrders: "pesanan menunggu",
    notifCheckOrders: "Semak pesanan anda",
    notifFoodRescued: "makanan diselamatkan",
    notifViewImpact: "Lihat impak alam sekitar anda",
    notifCO2Saved: "CO₂ dikurangkan",
    notifPendingPickup: "pesanan sedia untuk diambil",
    notifGoToOrders: "Pergi ke pesanan anda",
    notifOrdersCompleted: "pesanan selesai",
    notifSaved: "dijimatkan setakat ini",
    notifKeepSaving: "Terus jimat dengan JimatMakan!",
    esgCheckout: "Pembayaran Laporan ESG",
    esgPurchaseSuccess: "Laporan Dimuat Turun!",
    esgPurchaseSuccessDesc: "Laporan Impak ESG anda telah dijana dan dimuat turun ke peranti anda.",
    backToActivity: "Kembali ke Aktiviti",
    esgReportIncludes: "Laporan termasuk",
    esgMonthlyBreakdown: "Termasuk data pecahan bulanan",
    esgTotal: "Jumlah",
    esgPayAndDownload: "Bayar & Muat Turun Laporan",
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>("en");

  const t = useCallback(
    (key: TranslationKey) => translations[lang][key] || key,
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
